[build-system]
requires = ['cmake>=3.13', 'dune-fem@git+https://gitlab.dune-project.org/dune-fem/dune-fem.git', 'dune-grid@git+https://gitlab.dune-project.org/core/dune-grid.git', 'ninja', 'pip', 'requests', 'scikit-build', 'setuptools', 'wheel']
build-backend = 'setuptools.build_meta'
