name: Coding style

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install clang-format
          pip install pylint
        shell: bash

      - name: pylint
        working-directory: ${{ github.workspace }}
        run: |
          pylint --rcfile=pylintrc python

      - name: clang-format
        working-directory: ${{ github.workspace }}
        run: |
          find . -name '*.hh' -or -name '*.cc' | xargs clang-format --style=google --dry-run --Werror
