name: test

on: push

env:
  BUILD_TYPE: Release

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update
            sudo apt install libopenmpi-dev openmpi-bin libsuitesparse-dev gmsh libboost-all-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew update
            brew install openmpi suite-sparse gmsh boost
          fi
        shell: bash

      - name: Clone modules
        run: |
          cd ${{ github.workspace }}/..
          mkdir dune-common dune-geometry dune-grid dune-localfunctions dune-istl dune-alugrid dune-fem
          git clone --branch releases/2.8 https://gitlab.dune-project.org/core/dune-common.git dune-common
          git clone --branch releases/2.8 https://gitlab.dune-project.org/core/dune-geometry.git dune-geometry
          git clone --branch releases/2.8 https://gitlab.dune-project.org/core/dune-grid.git dune-grid
          git clone --branch releases/2.8 https://gitlab.dune-project.org/core/dune-localfunctions.git dune-localfunctions
          git clone --branch releases/2.8 https://gitlab.dune-project.org/core/dune-istl.git dune-istl
          git clone --branch releases/2.8 https://gitlab.dune-project.org/extensions/dune-alugrid.git dune-alugrid
          git clone --branch releases/2.8 https://gitlab.dune-project.org/dune-fem/dune-fem.git dune-fem

      - name: Configure and build modules
        run: |
          cd ${{ github.workspace }}/..
          python3 -m venv dune-venv
          source dune-venv/bin/activate
          ./dune-common/bin/dunecontrol --opts=dune-mmesh/cmake/config.opts all
          ./dune-common/bin/dunecontrol --opts=dune-mmesh/cmake/config.opts make install_python
          python dune-common/bin/setup-dunepy.py --opts=dune-mmesh/cmake/config.opts

      - name: Run python tests
        run: |
          cd ${{ github.workspace }}/..
          source dune-venv/bin/activate
          python -m dune.mmesh test

      - name: Build tests
        working-directory: ${{ github.workspace }}/build-cmake/
        run: make build_tests

      - name: Test
        working-directory: ${{ github.workspace }}/build-cmake/
        run: |
         source ../../dune-venv/bin/activate
         make test
